name: Deployment (Container)

on:
  push:
    branches:
      - main
      - dev

env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container:
      image: node:20-slim
    env:
      MONGODB_URI: mongodb+srv://${{ secrets.MONGODB_USERNAME }}:${{ secrets.MONGODB_PASSWORD }}@cluster0.e0ebl1g.mongodb.net/?retryWrites=true&w=majority
      MONGODB_DB_NAME: gha-demo
      PORT: 8080
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: |
          echo "Deploying..."
